# Generated by Django 5.2.1 on 2025-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_eventticket_organization_visitor_delete_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visitors',
            field=models.ManyToManyField(related_name='events', through='core.EventTicket', to='core.visitor'),
        ),
    ]
