# Generated by Django 5.2.1 on 2025-07-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
    ]
