# Generated by Django 5.2.1 on 2025-06-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_eventticket_status_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventticket',
            unique_together={('user', 'event')},
        ),
    ]
