# Generated by Django 5.2.1 on 2025-07-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250712_1502'),
    ]

    operations = [
    ]
