# Generated by Django 5.2.1 on 2025-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_eventticket_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_qr_codes/'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='ticket_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('EARLY_BIRD', 'Early Bird')], default='STANDARD', max_length=50),
        ),
    ]
