# Generated by Django 5.2.1 on 2025-06-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_groups_organization_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('used', 'Used')], default='active', max_length=20),
        ),
    ]
